settings_version = 1
default_profile = "vietnamese"

[anki]
vocabulary_model = "Vocabulary"
grammar_model = "Grammar"

[profiles.vietnamese]
study_language = "Vietnamese"
native_language = "English"
deck = "Vietnamese"
analysis_min_level = "A1"
analysis_max_level = "B2"

[profiles.french]
study_language = "French"
native_language = "English"
deck = "French"
analysis_min_level = "A1"
analysis_max_level = "B2"
